# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/sbin/cmake

# The command to remove a file.
RM = /usr/sbin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dev/workspace/container_state

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dev/workspace/container_state

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/sbin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/sbin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dev/workspace/container_state/CMakeFiles /home/dev/workspace/container_state//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dev/workspace/container_state/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named STATIClib

# Build rule for target.
STATIClib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 STATIClib
.PHONY : STATIClib

# fast build rule for target.
STATIClib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STATIClib.dir/build.make CMakeFiles/STATIClib.dir/build
.PHONY : STATIClib/fast

#=============================================================================
# Target rules for targets named SHAREDlib

# Build rule for target.
SHAREDlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SHAREDlib
.PHONY : SHAREDlib

# fast build rule for target.
SHAREDlib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SHAREDlib.dir/build.make CMakeFiles/SHAREDlib.dir/build
.PHONY : SHAREDlib/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/MAX.o: src/MAX.cc.o
.PHONY : src/MAX.o

# target to build an object file
src/MAX.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STATIClib.dir/build.make CMakeFiles/STATIClib.dir/src/MAX.cc.o
.PHONY : src/MAX.cc.o

src/MAX.i: src/MAX.cc.i
.PHONY : src/MAX.i

# target to preprocess a source file
src/MAX.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STATIClib.dir/build.make CMakeFiles/STATIClib.dir/src/MAX.cc.i
.PHONY : src/MAX.cc.i

src/MAX.s: src/MAX.cc.s
.PHONY : src/MAX.s

# target to generate assembly for a file
src/MAX.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STATIClib.dir/build.make CMakeFiles/STATIClib.dir/src/MAX.cc.s
.PHONY : src/MAX.cc.s

src/MIN.o: src/MIN.cc.o
.PHONY : src/MIN.o

# target to build an object file
src/MIN.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SHAREDlib.dir/build.make CMakeFiles/SHAREDlib.dir/src/MIN.cc.o
.PHONY : src/MIN.cc.o

src/MIN.i: src/MIN.cc.i
.PHONY : src/MIN.i

# target to preprocess a source file
src/MIN.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SHAREDlib.dir/build.make CMakeFiles/SHAREDlib.dir/src/MIN.cc.i
.PHONY : src/MIN.cc.i

src/MIN.s: src/MIN.cc.s
.PHONY : src/MIN.s

# target to generate assembly for a file
src/MIN.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SHAREDlib.dir/build.make CMakeFiles/SHAREDlib.dir/src/MIN.cc.s
.PHONY : src/MIN.cc.s

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cc.s
.PHONY : src/main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SHAREDlib"
	@echo "... STATIClib"
	@echo "... main"
	@echo "... src/MAX.o"
	@echo "... src/MAX.i"
	@echo "... src/MAX.s"
	@echo "... src/MIN.o"
	@echo "... src/MIN.i"
	@echo "... src/MIN.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

